export const SITE_NAME = "Gatrad Krupa Tours & Travels"
export const SITE_TITLE = SITE_NAME + " - Best Travel Agent in Kutch"
export const HQ_ADDRESS = "Mandvi Nagar Pakila Office No. 111, Mandvi Layja Road, Mandvi Kutch, Gujarat, India 370465"
export const MO_NUMBER = "+913369029285"
export const MO_NUMBER_STR = "033690 29285"
export const RATING_URL = "https://g.page/r/CW2POp9xVqwfEBM/review"
export const BASE_URL = "https://gatradkrupatourstravels.com"
